# Generated by Django 5.2.1 on 2025-07-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesapayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mpesa Payment', 'verbose_name_plural': 'Mpesa Payments'},
        ),
    ]
