# Generated by Django 5.2.1 on 2025-06-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporters_app', '0002_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='people',
            field=models.PositiveIntegerField(),
        ),
    ]
