# Generated by Django 5.2.1 on 2025-07-18 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporters_app', '0005_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 8, 36, 21, 820400, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
